---
sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get -q update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -q -y docker-ce
  - ssh-keygen -f id_rsa -t rsa -b 4096 -C "davidjosephcain@gmail.com" -N ''

install:
  - pip install -r requirements-dev.txt

cache: pip

script:
  - molecule test
