---

- name: Provision a {{ root_name }} db server
  hosts: dbservers
  become: true
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: true
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
  module_defaults:
    apt:
      force_apt_get: true

  roles:
    - base
    - db
