---

- name: Configure an instance running the MITOC Trips infrastructure
  hosts: all
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/production.yml

  roles:
    - base
    - rabbitmq
    - web
    - celery
    - nginx
