---

- name: Configure an instance running the MITOC Trips infrastructure
  hosts: all
  become: true
  become_user: root
  remote_user: ubuntu
  vars:
    - setup_git_repo: true
    - update_apt_cache: true
  vars_files:
    - env_vars/base.yml
    - env_vars/production.yml
  module_defaults:
    apt:
      force_apt_get: true

  roles:
    - security
    - base
    - certbot
    - rabbitmq
    - web
    - flask
    - celery
    - nginx
