---

- name: Initial configuration for a {{ root_name }} server
  hosts: all
  become: true
  become_user: root
  remote_user: root
  vars:
    - update_apt_cache: true
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
    - roles/base/defaults/main.yml
  module_defaults:
    apt:
      force_apt_get: true

  roles:
    - security
