---

- name: Create a {{ root_name }} virtual machine via vagrant
  hosts: all
  become: true
  become_user: root
  remote_user: vagrant
  vars:
    - update_apt_cache: true
    - disable_gsheets: '1'
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - security
    - base
    - avahi
    - db
    - rabbitmq
    - web
    - celery
    - nginx
    - flask
