---

git_repo: https://github.com/DavidCain/mitoc-trips.git
setup_git_repo: yes

project_name: trips
application_name: ws



# Database settings.
# Hard-coded as the application name, but this is how it's configured on RDS
db_user: "ws"
db_name: "ws"
auth_db_name: "auth_db"


# RabbitMQ settings.
# (We'll always run RabbitMQ on the same server, regardless of deployment)
rabbitmq_server_name: "{{ inventory_hostname }}"
broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@localhost/{{ rabbitmq_application_vhost }}"

# Application settings
run_django_db_migrations: yes
run_django_collectstatic: yes
django_settings_file: "{{ application_name }}.settings" # Dev/prod determined by envvar


# Worker settings
# For consistency, keep workers constant across dev, prod, and local
# (Load is always fairly low, regardless of environment)
gunicorn_num_workers: 3  # A good rule to follow is 2 x number of CPUs + 1
celery_num_workers: 2
