---

git_branch: master

# IP address of EC2 instance serving MITOC Trips
ec2_ip: 54.166.139.248

mitoc_bursar_name: "Hannah Varner"

# Security settings
# No need to have our own firewall - port access is controlled in AWS
enable_ufw: false
# We've manually configured SSH
force_ssh_authentication: false
use_more_restrictive_sshd_config: true


# Something about our django-pipeline configuration requires too much CPU
# Trying to run `collectstatic` on the remote host will crash the server
# (Instead, we'll collect assets locally and sync to the server)
run_django_collectstatic: false


# MITOC Trips database settings.
db_host: REDACTED
db_password: REDACTED
master_db_password: REDACTED


# Gear database credentials (for querying current membership status)
gear_db_host: REDACTED
gear_db_user: REDACTED
gear_db_password: REDACTED
gear_db_name: REDACTED

# Credentials for gear database when we migrate over to Postgres
# (These currently aren't used in production)
pg_gear_db_host: REDACTED
pg_gear_db_user: REDACTED
pg_gear_db_password: REDACTED
pg_gear_db_name: REDACTED


# Served to clients for reporting Content Security Policy violations
security_header_endpoint: "https://sentry.io/api/104648/security/?sentry_key=8ca35907a538416cbfad696d187acdc0"
# Used privately in Python source for reporting server-side violations
raven_dsn: REDACTED
flask_raven_dsn: REDACTED


# DocuSign settings
docusign_api_base: "https://www.docusign.net/restapi/v2/"
docusign_waiver_template_id: "ce1ea05f-cea0-4f60-ab70-0464baf7b600"
docusign_username: REDACTED
docusign_password: REDACTED
docusign_integrator_key: REDACTED

# This is the SSL fingerprint of the DocuSign Connect certificate, obtained by:
#     openssl x509 -in <cert> -noout -fingerprint
# Certificates are available at:
# https://trust.docusign.com/en-us/trust-certifications/docusign-public-certificates/
docusign_client_fingerprint: 70d6116636eef6a32ef196b8e6d86fb17cffacaa


# CyberSource settings
verify_cybersource_signature: "false"  # Will rely on IP check


# Google API settings
# oauth_client_email: mitoc-discounts@appspot.gserviceaccount.com
# oauth_client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/mitoc-discounts%40appspot.gserviceaccount.com
oauth_private_key_id: REDACTED

oauth_private_key: REDACTED

# Express these variables again so that they can be JSON serialized
# (to_json will not work on encrypted variables - it serializes the encrypted string!)
oauth_config:
  private_key_id: "{{ oauth_private_key_id }}"
  private_key: "{{ oauth_private_key }}"

# SES settings
ses_user: REDACTED
ses_password: REDACTED


# Setting this to 1 will restart the Gunicorn process each time
# you make a request, basically reloading the code. Very handy
# when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0


# RabbitMQ settings.
rabbitmq_admin_user: REDACTED
rabbitmq_admin_password: REDACTED
rabbitmq_application_password: REDACTED


# Nginx settings
nginx_server_name: mitoc-trips.mit.edu
api_url: api.mitoc.org
mutual_tls_api_url: docusign.mitoc.org
nginx_strong_dh_group: true
nginx_use_letsencrypt: true


# Application settings
django_secret_key: REDACTED
prng_seed_secret: REDACTED
membership_secret_key: REDACTED


# Public certificate for mitoc-trips.mit.edu
ssl_crt: |
  -----BEGIN CERTIFICATE-----
  MIIHLjCCBhagAwIBAgIRANX3fVBTFVouSVidBLIE5MwwDQYJKoZIhvcNAQELBQAwdjELMAkGA1UE
  BhMCVVMxCzAJBgNVBAgTAk1JMRIwEAYDVQQHEwlBbm4gQXJib3IxEjAQBgNVBAoTCUludGVybmV0
  MjERMA8GA1UECxMISW5Db21tb24xHzAdBgNVBAMTFkluQ29tbW9uIFJTQSBTZXJ2ZXIgQ0EwHhcN
  MTkxMjI3MDAwMDAwWhcNMjExMjI2MjM1OTU5WjCB4TELMAkGA1UEBhMCVVMxDjAMBgNVBBETBTAy
  MTM5MRYwFAYDVQQIEw1NYXNzYWNodXNldHRzMRIwEAYDVQQHEwlDYW1icmlkZ2UxHTAbBgNVBAkT
  FDc3IE1hc3NhY2h1c2V0dHMgQXZlMS4wLAYDVQQKEyVNYXNzYWNodXNldHRzIEluc3RpdHV0ZSBv
  ZiBUZWNobm9sb2d5MSkwJwYDVQQLDCBJbmZvcm1hdGlvbiBTeXN0ZW1zICYgVGVjaG5vbG9neTEc
  MBoGA1UEAxMTbWl0b2MtdHJpcHMubWl0LmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
  ggEBALt3aDj3jdtCH/OraHe5y7xU4+0LNv1YICf+mfJ1Y515mICAIrAfBrMPxum42zyy5trx+exU
  jGceFHdhkHSNWvBfMTZt1U0I0ohElI0bAeSCVPa13Fgv1fljOjOHEwUAPQtwzytf6AhnLLNxYkN7
  GA2yupD+tosZN9fuRqdfkWu3tyOhaoPULhxB++thjX6UDkWueCYz+vZ0lnu2CBkqlc5IsKWS7GnU
  J5rzBle5FwKXuBXw5hYvOy3qRARN2bJrOxF8ETiEIhjhr2wu6wfErW56PCJunTwWnAjK7ExWtOZM
  kkwKbIGXaHQri49mm8wmNy/5UeVqi87YPpLlCYFRAwUCAwEAAaOCA0kwggNFMB8GA1UdIwQYMBaA
  FB4Fo3ePbJbiW4dLprSGrHEADOc4MB0GA1UdDgQWBBSs7AkoZ4vKw2IZe27ICPYQ6d0KSDAOBgNV
  HQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
  ZwYDVR0gBGAwXjBSBgwrBgEEAa4jAQQDAQEwQjBABggrBgEFBQcCARY0aHR0cHM6Ly93d3cuaW5j
  b21tb24ub3JnL2NlcnQvcmVwb3NpdG9yeS9jcHNfc3NsLnBkZjAIBgZngQwBAgIwRAYDVR0fBD0w
  OzA5oDegNYYzaHR0cDovL2NybC5pbmNvbW1vbi1yc2Eub3JnL0luQ29tbW9uUlNBU2VydmVyQ0Eu
  Y3JsMHUGCCsGAQUFBwEBBGkwZzA+BggrBgEFBQcwAoYyaHR0cDovL2NydC51c2VydHJ1c3QuY29t
  L0luQ29tbW9uUlNBU2VydmVyQ0FfMi5jcnQwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0
  cnVzdC5jb20wHgYDVR0RBBcwFYITbWl0b2MtdHJpcHMubWl0LmVkdTCCAX4GCisGAQQB1nkCBAIE
  ggFuBIIBagFoAHcAfT7y+I//iFVoJMLAyp5SiXkrxQ54CX8uapdomX4i8NcAAAFvR/4yeQAABAMA
  SDBGAiEAtYw6avRsarF36ctVOdCDCmi88UX7YPHp/qKZLwzPCvQCIQCs1OFsYtJ8XfjTKu7ND5yu
  x4MHaO89xDLOrYkX/78qUgB1AESUZS6w7s6vxEAH2Kj+KMDa5oK+2MsxtT/TM5a1toGoAAABb0f+
  Mk4AAAQDAEYwRAIgVX3oqCIaAV4xSBMEDtIUEt54LlwgJNfXur3VcrhHOs0CIDHVr30hH7P7jhKm
  D4u9lAlyeeFwLSnFFRRYRUhqoND3AHYAb1N2rDHwMRnYmQCkURX/dxUcEdkCwQApBo2yCJo32RMA
  AAFvR/4yUAAABAMARzBFAiEAsq4wa4rdk9WZUFVegPlmyVB+k1fjU6F/DkwNY9teU00CIBnB29H0
  bTDRvE0X3KjZf0lhTnkI0sxRY9COSFW/nxrTMA0GCSqGSIb3DQEBCwUAA4IBAQBFgTfYsOA1FTS5
  /AXeniiWVLKpoFXniXU/YV0pPI9jeOEh/Pfr3GE5XzyfFzgMYfynoJz0vFeU0UkhMHI9moFD97HS
  6KphCdnD6ausszjoP88UBNDMrckN7D+jv5bbJ729rDjlCOOP9HjAtCtLpbD5jezHgfrNaIUPCUik
  V8DoXgS3ds6wQxDV3UERs3mKdngCWBRcSiYoSUu5VanntGMHV8X0y7xQwuvw2afqhLllblkWRaBL
  R4BhEXnSCDerApMTkS7YdLtRNntCmDeGf3sI6SfvbFTLm5M4CJ7mGacAQLcS6m/Gu/kt6WgOAvs4
  2M3Pkj0jtZvCx9vsV1bYaqwp
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIF+TCCA+GgAwIBAgIQRyDQ+oVGGn4XoWQCkYRjdDANBgkqhkiG9w0BAQwFADCBiDELMAkGA1UE
  BhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0plcnNleSBDaXR5MR4wHAYDVQQK
  ExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNVBAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNh
  dGlvbiBBdXRob3JpdHkwHhcNMTQxMDA2MDAwMDAwWhcNMjQxMDA1MjM1OTU5WjB2MQswCQYDVQQG
  EwJVUzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBBcmJvcjESMBAGA1UEChMJSW50ZXJuZXQy
  MREwDwYDVQQLEwhJbkNvbW1vbjEfMB0GA1UEAxMWSW5Db21tb24gUlNBIFNlcnZlciBDQTCCASIw
  DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJwb8bsvf2MYFVFRVA+exU5NEFj6MJsXKZDmMwys
  E1N8VJG06thum4ltuzM+j9INpun5uukNDBqeso7JcC7vHgV9lestjaKpTbOc5/MZNrun8XzmCB5h
  J0R6lvSoNNviQsil2zfVtefkQnI/tBPPiwckRR6MkYNGuQmm/BijBgLsNI0yZpUn6uGX6Ns1oytW
  61fo8BBZ321wDGZq0GTlqKOYMa0dYtX6kuOaQ80tNfvZnjNbRX3EhigsZhLI2w8ZMA0/6fDqSl5A
  B8f2IHpTeIFken5FahZv9JNYyWL7KSd9oX8hzudPR9aKVuDjZvjs3YncJowZaDuNi+L7RyMLfzcC
  AwEAAaOCAW4wggFqMB8GA1UdIwQYMBaAFFN5v1qqK0rPVIDh2JvAnfKyA2bLMB0GA1UdDgQWBBQe
  BaN3j2yW4luHS6a0hqxxAAznODAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADAd
  BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwGwYDVR0gBBQwEjAGBgRVHSAAMAgGBmeBDAEC
  AjBQBgNVHR8ESTBHMEWgQ6BBhj9odHRwOi8vY3JsLnVzZXJ0cnVzdC5jb20vVVNFUlRydXN0UlNB
  Q2VydGlmaWNhdGlvbkF1dGhvcml0eS5jcmwwdgYIKwYBBQUHAQEEajBoMD8GCCsGAQUFBzAChjNo
  dHRwOi8vY3J0LnVzZXJ0cnVzdC5jb20vVVNFUlRydXN0UlNBQWRkVHJ1c3RDQS5jcnQwJQYIKwYB
  BQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20wDQYJKoZIhvcNAQEMBQADggIBAC0RBjjW
  29dYaK+qOGcXjeIT16MUJNkGE+vrkS/fT2ctyNMU11ZlUp5uH5gIjppIG8GLWZqjV5vbhvhZQPwZ
  sHURKsISNrqOcooGTie3jVgU0W+0+Wj8mN2knCVANt69F2YrA394gbGAdJ5fOrQmL2pIhDY0jqco
  74fzYefbZ/VS29fR5jBxu4uj1P+5ZImem4Gbj1e4ZEzVBhmO55GFfBjRidj26h1oFBHZ7heDH1Bj
  zw72hipu47Gkyfr2NEx3KoCGMLCj3Btx7ASn5Ji8FoU+hCazwOU1VX55mKPU1I2250LoRCASN18J
  yfsD5PVldJbtyrmz9gn/TKbRXTr80U2q5JhyvjhLf4lOJo/UzL5WCXEDSmyj4jWG3R7Z8TED9xNN
  CxGBMXnMete+3PvzdhssvbORDwBZByogQ9xL2LUZFI/ieoQp0UM/L8zfP527vWjEzuDN5xwxMnhi
  +vCToh7J159o5ah29mP+aJnvujbXEnGanrNxHzu+AGOePV8hwrGGG7hOIcPDQwkuYwzN/xT29iLp
  /cqf9ZhEtkGcQcIImH3boJ8ifsCnSbu0GB9L06Yqh7lcyvKDTEADslIaeSEINxhO2Y1fmcYFX/Fq
  rrp1WnhHOjplXuXE0OPa0utaKC25Aplgom88L2Z8mEWcyfoB7zKOfD759AN7JKZWCYwk
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIFdzCCBF+gAwIBAgIQE+oocFv07O0MNmMJgGFDNjANBgkqhkiG9w0BAQwFADBvMQswCQYDVQQG
  EwJTRTEUMBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAsTHUFkZFRydXN0IEV4dGVybmFsIFRU
  UCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBFeHRlcm5hbCBDQSBSb290MB4XDTAwMDUzMDEw
  NDgzOFoXDTIwMDUzMDEwNDgzOFowgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5
  MRQwEgYDVQQHEwtKZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBOZXR3b3JrMS4w
  LAYDVQQDEyVVU0VSVHJ1c3QgUlNBIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIICIjANBgkqhkiG
  9w0BAQEFAAOCAg8AMIICCgKCAgEAgBJlFzYOw9sIs9CsVw127c0n00ytUINh4qogTQktZAnczomf
  zD2p7PbPwdzx07HWezcoEStH2jnGvDoZtF+mvX2do2NCtnbyqTsrkfjib9DsFiCQCT7i6HTJGLSR
  1GJk23+jBvGIGGqQIjy8/hPwhxR79uQfjtTkUcYRZ0YIUcuGFFQ/vDP+fmyc/xadGL1RjjWmp2bI
  cmfbIWax1Jt4A8BQOujM8Ny8nkz+rwWWNR9XWrf/zvk9tyy29lTdyOcSOk2uTIq3XJq0tyA9yn8i
  NK5+O2hmAUTnAU5GU5szYPeUvlM3kHND8zLDU+/bqv50TmnHa4xgk97Exwzf4TKuzJM7UXiVZ4vu
  PVb+DNBpDxsP8yUmazNt925H+nND5X4OpWaxKXwyhGNVicQNwZNUMBkTrNN9N6frXTpsNVzbQdcS
  2qlJC9/YgIoJk2KOtWbPJYjNhLixP6Q5D9kCnusSTJV882sFqV4Wg8y4Z+LoE53MW4LTTLPtW//e
  5XOsIzstAL81VXQJSdhJWBp/kjbmUZIO8yZ9HE0XvMnsQybQv0FfQKlERPSZ51eHnlAfV1SoPv10
  Yy+xUGUJ5lhCLkMaTLTwJUdZ+gQek9QmRkpQgbLevni3/GcV4clXhB4PY9bpYrrWX1Uu6lzGKAgE
  JTm4Diup8kyXHAc/DVL17e8vgg8CAwEAAaOB9DCB8TAfBgNVHSMEGDAWgBStvZh6NLQm9/rEJlTv
  A73gJMtUGjAdBgNVHQ4EFgQUU3m/WqorSs9UgOHYm8Cd8rIDZsswDgYDVR0PAQH/BAQDAgGGMA8G
  A1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAGBgRVHSAAMEQGA1UdHwQ9MDswOaA3oDWGM2h0dHA6
  Ly9jcmwudXNlcnRydXN0LmNvbS9BZGRUcnVzdEV4dGVybmFsQ0FSb290LmNybDA1BggrBgEFBQcB
  AQQpMCcwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20wDQYJKoZIhvcNAQEM
  BQADggEBAJNl9jeDlQ9ew4IcH9Z35zyKwKoJ8OkLJvHgwmp1ocd5yblSYMgpEg7wrQPWCcR23+Wm
  gZWnRtqCV6mVksW2jwMibDN3wXsyF24HzloUQToFJBv2FAY7qCUkDrvMKnXduXBBP3zQYzYhBx9G
  /2CkkeFnvN4ffhkUyWNnkepnB2u0j4vAbkN9w6GAbLIevFOFfdyQoaS8Le9Gclc1Bb+7RrtubTeZ
  tv8jkpHGbkD4jylW6l/VXxRTrPBPYer3IsynVgviuDQfJtl7GQVoP7o81DgGotPmjw7jtHFtQELF
  hLRAlSv0ZaBIefYdgWOWnU914Ph85I6p0fKtirOMxyHNwu8=
  -----END CERTIFICATE-----

# Private key for mitoc-trips.mit.edu
ssl_key: REDACTED
