---

- name: Install additional packages
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: present
    name:
      - libpq-dev
      - "{{ virtualenv_python_version + '-dev' }}"
      - mysql-client
      - libssl-dev
      - libmysqlclient-dev

- name: Install pgcli
  pip: name=pgcli
  tags: packages
