---

- name: Install the GPG key for Node
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  tags: makestuff

- name: Install Node.js 12 LTS repository  # (12.x is EOL in April, 2022)
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_12.x bionic main"
    state: present
    update_cache: true
  tags: makestuff

- name: Make sure node & npm are installed
  apt:
    name:
      - nodejs
    state: present
  tags:
    - packages

- name: Ensure JS+CSS compressors installed
  npm: name={{ item }} global=yes
  with_items:
    - uglify-js
    - yuglify
  tags:
    - packages

# Note: this is the legacy npm bundle
- name: Install dependencies with npm
  npm:
    path: "{{ project_path }}"
    production: true

- name: Create a script to make the application
  template: src=make_project.j2
            dest={{ virtualenv_path }}/bin/make_project
            mode=0755

# Preferably, we'd just use the `make` module directly instead of a template + command.
# However, we invoke poetry as part of our `make` targets.
# To ensure that dependencies get installed into the venv, we must activate the venv first.
- name: Make the project
  command: "{{ virtualenv_path }}/bin/make_project"

- name: Copy over the Google API credentials
  template: src=oauth_credentials.j2
            dest={{ project_path }}/oauth_credentials.json
            owner=root
            group=root
            mode=0440
  when: oauth_config is defined

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
    database: "{{ item }}"
  environment: "{{ django_environment }}"
  when: run_django_db_migrations is defined and run_django_db_migrations
  with_items:
    - default
    - auth_db
  tags: django.migrate

- name: Run Django collectstatic
  django_manage:
    command: "collectstatic -v 0 --no-input"
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_collectstatic is defined and run_django_collectstatic
  notify: restart application
  tags: django.collectstatic
